#pragma once
#define SIMPLEX_ABOUT_COMMIT_IDENTIFER "fed91f5"
#define SIMPLEX_ABOUT_VERSION_MAJOR 1
#define SIMPLEX_ABOUT_VERSION_MINOR 0
#define SIMPLEX_ABOUT_VERSION_PATCH 71
#define SIMPLEX_ABOUT_PROJECT_NAME "Simplex"
#define SIMPLEX_ABOUT_ENGINE_NAME "SimplexVK"