#pragma once
#define SIMPLEX_ABOUT_COMMIT_IDENTIFER "d9e21f0"
#define SIMPLEX_ABOUT_VERSION_MAJOR 1
#define SIMPLEX_ABOUT_VERSION_MINOR 0
#define SIMPLEX_ABOUT_VERSION_PATCH 58
#define SIMPLEX_ABOUT_PROJECT_NAME "Simplex"
#define SIMPLEX_ABOUT_ENGINE_NAME "SimplexVK"