#pragma once
#define SIMPLEX_ABOUT_COMMIT_IDENTIFER "8280cdc"
#define SIMPLEX_ABOUT_VERSION_MAJOR 1
#define SIMPLEX_ABOUT_VERSION_MINOR 0
#define SIMPLEX_ABOUT_VERSION_PATCH 105
#define SIMPLEX_ABOUT_PROJECT_NAME "Simplex"
#define SIMPLEX_ABOUT_ENGINE_NAME "SimplexVK"